Basic portfolio website : Use media queries to make sure that website displays correctly on desktop screens. (Desktop: 768px or wider).
EmekaEmmanuel/res_portfolio pull request #5
Opened 2022-12-08 16:50 UTC by EmekaEmmanuel

Portfolio Setup is a simple portfolio website with these sections contained in this project;
- Toolbar
- Headline section (right after the header).
- Works
- About myself
- Contact me
The layout was done using css flexbox and css grid, button interactions implemented.
Use media queries to make sure that website displays correctly on desktop screens. (Desktop: 768px or wider).

2022-12-08 18:34 UTC, amejid requested changes
Hi @EmekaEmmanuel, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
- Correct use of Github flow :heavy_check_mark: 
- Good commit messages :heavy_check_mark: 
- Linter checks passing :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 18:34 UTC, amejid commented on index.html
>      <section class="works_section">
- [ ] Good job applying media queries to make the website responsive. While doing so we should also make sure that we maintain the mobile layout. 🥸️
Kindly update the gap between your projects and the margin on the sides as per the Figma template.

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/17243325/206525296-2acd0af6-7b17-407b-bd0e-d9532215eb4f.png" width="300">|<img src="https://user-images.githubusercontent.com/17243325/206525281-fa08b712-5f95-4203-9a76-95a9a9fdd8cd.png" width="300">|

2022-12-08 18:34 UTC, amejid commented on index.html
> +        </article>
- [ ] One of the objectives of this project is to understand how to parse Figma templates precisely. 🤝️
Kindly update the gap between the paragraph and the social icons to match the Figma design.

- Your Design
![Screenshot from 2022-12-08 20-21-18](https://user-images.githubusercontent.com/17243325/206527584-12244ea9-ceba-49fe-a5f7-149de45c2cce.png)

- Figma Design
![Screenshot from 2022-12-08 20-20-35](https://user-images.githubusercontent.com/17243325/206527771-48fe11e0-d928-4da8-b662-8c9ce298ca8e.png)

2022-12-08 18:34 UTC, amejid commented on index.html
> +            </div>
- [ ] Good job alternating the image and project description. I think there's a little more to do to match the Figma design.
Kindly check the whitespace to the left and right of the component. 😎️

- Your Design
![Screenshot from 2022-12-08 20-26-00](https://user-images.githubusercontent.com/17243325/206531389-4d42cee6-72c2-4c66-b4d0-d51d0814a45e.png)

- Figma Design
![Screenshot from 2022-12-08 20-25-04](https://user-images.githubusercontent.com/17243325/206531604-93ca0d01-6e94-4db4-800e-166f9f9310db.png)

2022-12-08 18:34 UTC, amejid commented on index.html
> +    <section class="about_self_section bg_color7">
Nice job so far on the about section. I think some small details are missing when compared to the Figma template. ✍️
- [ ] Kindly use `40%` width on the left section and `60%` on the right one to achieve the Design.
- [ ] Kindly increase the width of the cards that hold HTML, CSS, and Javascript icons and make the icons align to the left inside the card. Please update the text `color` below the icon images.
- [ ] I think a fixed with is being applied to the paragraph in the left section. Kindly update the `font-size` and remove the fixed width so the paragraph can span the whole parent element.

- Your Design
![Screenshot from 2022-12-08 20-30-52](https://user-images.githubusercontent.com/17243325/206535271-45f13f26-e446-4f06-bd03-5e91586095bd.png)

- Figma Design
![Screenshot from 2022-12-08 20-30-13](https://user-images.githubusercontent.com/17243325/206535405-24351987-2c02-4d75-a1ee-85a04da60a0f.png)

2022-12-08 18:34 UTC, amejid commented on index.html
> +        <article class="contact_section">
You are almost there with the design. There are some small details remaining to achieve perfection. 🤓️
- [ ] Kindly check if the correct background image for this section is being used.
- [ ] Kindly make sure the paragraph and the `form` element are positioned in the center of the screen. You can give these elements a `max-width` property to achieve this alignment.

- Your Design
![Screenshot from 2022-12-08 20-33-11](https://user-images.githubusercontent.com/17243325/206537507-0a7acdc2-4849-45a1-a33a-2c86a5f9dfd5.png)

- Figma Design
![Screenshot from 2022-12-08 20-32-35](https://user-images.githubusercontent.com/17243325/206537584-1b44d7e1-c294-42ac-98d7-7e25c9055b64.png)

2022-12-09 14:09 UTC, DuaneDave approved these changes
Hi @EmekaEmmanuel 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Solid design 👍
✅ Quick implementation of requested change 👍 
✅ Meaningful commit history 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-12 12:31 UTC, merged